In [11]:
import numpy as np
import matplotlib.pyplot as plt
import math

# Problem 1
## Dataset Generation

Write a function to **generate a training set** of size $m$
- randomly generate a weight vector $w \in \mathbb{R}^{10}$, normalize length
- generate a training set $\{(x_i , y_i)\}$ of size m
  - $x_i$: random vector in $\mathbb{R}^{10}$ from $\textbf{N}(0, I)$
  - $y_i$: $\{0, +1\}$ with $P[y = +1] = \sigma(w \cdot x_i)$ and $P[y = 0] = 1 - \sigma(w \cdot x_i)$

In [29]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
     

def generate_vector(normalize=False):
    v = np.random.randn(10)
    if normalize:
        sum = 0
        for i in v:
            sum += i * i 
        norm = math.sqrt(sum)
        v = [i*1/norm for i in v]
    return v

def generate_label(x_i,w):
    #wT = np.transpose([w])
    wT = w
    print(wT)
    product = np.multiply(wT,x_i)
    print(product)
    y_i = sigmoid(product)
    print('yi' ,y_i)
    return

def generate_data(m):
    x = []
    for i in range(m):
        x.append(generate_vector(normalize=False))
    x = np.array(x)
    return x

generate_label(generate_vector(normalize=True),generate_data(3))

[[[ 1.78441465]
  [-1.08265882]
  [-0.84700042]]

 [[ 0.15305618]
  [ 2.08582468]
  [-0.63189148]]

 [[ 1.81752022]
  [ 0.71504748]
  [-2.23193366]]

 [[ 0.50336481]
  [ 0.97367901]
  [ 0.46134572]]

 [[ 0.74163771]
  [ 0.86432495]
  [-0.0887054 ]]

 [[ 1.75905748]
  [ 0.65647525]
  [-0.8702652 ]]

 [[-2.77813641]
  [-0.96664727]
  [-0.78778332]]

 [[-0.68928906]
  [ 0.61367299]
  [-1.04706238]]

 [[ 0.04755947]
  [-0.47593071]
  [ 0.81830973]]

 [[ 0.67359415]
  [-1.50718594]
  [-1.0945254 ]]]
[[[-1.1523599  -0.37513351  0.22809153 -0.33316487  0.71035883
   -0.37971191  0.27828802  0.56825846 -0.45926195  0.54072018]
  [ 0.69917192  0.22760495 -0.13839009  0.20214129 -0.43099638
    0.2303828  -0.16884583 -0.34477975  0.27864824 -0.32807144]
  [ 0.54698571  0.17806301 -0.10826723  0.15814193 -0.33718297
    0.18023622 -0.13209378 -0.2697328   0.21799589 -0.25666132]]

 [[-0.09884239 -0.03217666  0.0195643  -0.02857685  0.06093024
   -0.03256937  0.02386985  0.04874174 -0.03939268  0.

## Algorithm 1: logistic regression

The goal is to learn $w$.  Algorithm 1 is logistic
  regression (you may use the built-in method LogisticRegression for this. Use max_iter=1000).

## Algorithm 2: gradient descent with square loss

Define square loss as
$$L_i(w^{(t)}) = \frac{1}{2} \left( \sigma(w^{(t)} \cdot x) - y_i \right)^2$$

  Algorithm 2 is
  gradient descent with respect to square loss (code this
  up yourself -- run for 1000 iterations, use step size eta = 0.01).

## Algorithm 3: stochastic gradient descent with square loss
Similar to gradient descent, except we use the gradient at a single random training point every iteration.

## Evaluation

Measure error $\|w - \hat{w}\|_2$ for each method at different sample size. For any
  fixed value of $m$, choose many different $w$'s and average the
  values $\|w - 
  \hat{w}\|_2$ for Algorithms 1, 2 and 3.  Plot the results
  for for each algorithm as you make $m$ large (use $m=50, 100, 150, 200, 250$).
  Also record, for each algorithm, the time taken to run the overall experiment.

# Problem 2

In [3]:
from sklearn import datasets

In [4]:
cancer = datasets.load_breast_cancer()

For each depth in $1, \dots, 5$, instantiate an AdaBoost classifier with the base learner set to be a decision tree of that depth (set `n_estimators=10` and `learning_rate=1`), and then record the 10-fold cross-validated error on the entire breast cancer data set. Plot the resulting curve of accuracy against base classifier depth. Use $101$ as your random state for both the base learner as well as the AdaBoost classifier every time.